export { AuthorInterface } from './author'
export { BreadcrumbInterface } from './breadcrumb'
export { BlogItemInterface } from './blogItem'
export { ImageInterface } from './image'
export { TapeInterface } from './tape'
export { VillagerInterface } from './villager'