export const compliments = [
  "all i'm seeing is flames 😳",
  'are those new shoes? 💎',
  'had to do it to em 😏',
  'i knew it',
  "i'll remember for next time 🤝",
  'just WOW',
  'looks good on you! 💕',
  'keep up the drip my g 😮‍💨',
  'oh, you and i are going to get on',
  'only you could pull this off ✨',
  'really brings out your eyes',
  'PLEASE anything but this one 😩',
  "someone's looking good!",
  "scroll down already",
  'too clean 🛀',
  'what! come on 🏃🏻',
  'wow',
  'yeah i feel the same tbh',
  'slow down! you dropped this 👑',
  "you're on fire today 🥵"
];
